@MyWebAPI_HostAddress = http://localhost:5103

GET {{MyWebAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{MyWebAPI_HostAddress}}/weatherforecast/
Content-Type: application/json

{
    "date": "2023-10-10",
    "temperatureC": 25,
    "summary": "Warm"
}

###
PUT {{MyWebAPI_HostAddress}}/weatherforecast/1
Content-Type: application/json

{
    "date": "2023-10-11",
    "temperatureC": 30,
    "summary": "Hot"
}

###
DELETE {{MyWebAPI_HostAddress}}/weatherforecast/1